apiVersion: v1
data:
  nginx.conf: |
    # For more information on configuration, see:
    #   * Official English Documentation: http://nginx.org/en/docs/
    #   * Official Russian Documentation: http://nginx.org/ru/docs/

    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        client_max_body_size 500m;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   3600;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        #include /etc/nginx/conf.d/*.conf;



        proxy_hide_header 'X-XSS-Protection';
        proxy_hide_header 'X-Frame-Options';
        proxy_hide_header 'X-Content-Type-Options';
        proxy_hide_header 'Content-Security-Policy';


        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        server {

            gzip on;
            gzip_comp_level 5;
            gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/rss+xml text/javascript image/x-icon image/bmp image/svg+xml;
            gzip_proxied no-cache no-store private expired auth;
            gzip_min_length 1000;
            proxy_pass_header Server;

            #proxy_connect_timeout 600;
            #proxy_send_timeout 600;
            #proxy_read_timeout 600;
            #send_timeout 600;

            add_header X-XSS-Protection "1; mode=block";
            add_header X-Content-Type-Options nosniff;
            add_header X-Frame-Options SAMEORIGIN always;
            add_header Content-Security-Policy-Report-Only "default-src 'self'; connect-src 'self' 'unsafe-inline' https://cdn.plot.ly wss://appshell-dev.cde.fullstream.ai https://matomo-dev.cde.fullstream.ai ; script-src 'self' data: code.jquery.com 'unsafe-eval' 'unsafe-inline' https://matomo-dev.cde.fullstream.ai ; style-src 'self' 'unsafe-inline' fonts.googleapis.com; object-src 'none'; base-uri 'self'; font-src 'self' 'unsafe-inline' data: fonts.gstatic.com; frame-src 'self' https://matomo-dev.cde.fullstream.ai https://ss-kc-dev.cde.fullstream.ai https://www.figma.com https://aerion-uat.cde.fullstream.ai https://sparq-dev.np-0000177.npause1.bakerhughes.com https://aerion-qa.cde.fullstream.ai https://aerion-dev.cde.fullstream.ai; img-src 'self' data: blob: https://minio-s3.cde.fullstream.ai https://www.w3schools.com ; manifest-src 'self' https://gateway.zscalertwo.net; media-src 'self'; frame-ancestors 'self'; form-action 'self';";

            listen       0.0.0.0:80;
            server_name  your-domain-name;
            root         /usr/share/nginx/html;

            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;

            location / {
            }

            location /argocd {
             proxy_redirect off;
             proxy_pass http://argocd-server.argocd;
             proxy_http_version 1.1; # this is essential for chunked responses to work
             proxy_buffering    off;
             proxy_set_header   X-Real-IP $remote_addr;
             proxy_set_header   X-Scheme $scheme;
             proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header   Host $http_host;
            }

    }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config