apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/efs-mount-point/pgadmin-pv/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
  volumeName: pgadmin-pv
  storageClassName: manual
