apiVersion: v1
kind: Service
metadata:
  name: svc-bhsecurityservice
  labels:
    app: bhsecurityservice
spec:
  type: NodePort
  ports:
  - name: bhsecurityservice
    port: 80
    nodePort: 32281
    targetPort: 8080
  selector:
    app: dep-bhsecurity-service
