apiVersion: v1
kind: Service
metadata:
  name: svc-notification
  labels:
    app: notification
spec:
  type: NodePort
  ports:
  - name: notification
    port: 80
    nodePort: 30218
    targetPort: 3000
  - name: postgres-db
    port: 5432
    targetPort: 5432
  - name: health-port
    port: 5678
    targetPort: 5678
  selector:
    app: dep-notification
