apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config
data:
  notificationsvc.conf: |
    { 
              "FS-DEV": {
                "properties": {
                    "tenant_name":"FS-DEV",
                    "DB_HOST": "fsnpgd04.c6ooanpu2tgf.us-east-1.rds.amazonaws.com",
                    "DB_PORT": "5432",
                    "PG_TLS": "true",
                    "DB_USERNAME": "notifi",
                    "SMTP_USERNAME": "SVC-FS-Notification",
                    "SMTP_HOST": "smtphosthou.bakerhughes.com",
                    "SMTP_PORT": "587",
                    "SMTP_FROM": "SVC-FS-Notification@bakerhughes.com",
                    "SMTP_LOGS": "true",
                    "REDIS_STREAM_MSG_LENGTH": "50000",
                    "MAX_RETRIES" : "3",
                    "MAX_SUBJECT_LENGTH" : "255",
                    "MAX_BODY_LENGTH" : "500",
                    "MAX_NUMBER_OF_RECIPIENT" : "10",
                    "MAX_NUMBER_OF_ATTACHMENT" : "10",
                    "MAX_SIZE_OF_ATTACHMENT" : "15",
                    "MAX_NUMBER_OF_CC_RECIPIENT" : "10",
                    "MAX_NUMBER_OF_REPLY_TO": "10",
                    "TYPE_OF_ATTACHMENT" : "application/pdf,text/html,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain"
                    },
                "secrets":{
                    "SMTP_PASSWORD": "/volume/tenant-secret/SMTP_PASSWORD_FS_DEV",           
                    "DB_PASSWORD": "/volume/tenant-secret/DB_PASSWORD_FS_DEV",
                    "client_secret":"/volume/tenant-secret/CLIENT_SECRET_FS-DEV"
                }
            }         
    }

