apiVersion: v1
kind: Service
metadata:
  name: svc-keycloak
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
  - name: keycloak
    port: 80
    nodePort: 30080
    targetPort: 8080
  selector:
    app: dep-keycloak-svc
