apiVersion: v1
kind: Service
metadata:
  name: svc-case-alert-2-0
  labels:
    app: case-alert-2-0
spec:
  type: NodePort
  ports:
  - name: case-alert
    port: 80
    nodePort: 30224
    targetPort: 8000
  - name: postgres-db
    port: 5432
    targetPort: 5432
  selector:
    app: dep-case-alert-2-0
