apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
        user nginx;
        worker_processes auto;
        #error_log /var/log/nginx/error.log;
        error_log stderr warn;
        pid /run/nginx.pid;

        # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
        include /usr/share/nginx/modules/*.conf;

        events {
        worker_connections 1024;
           }

        http {
        #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                     # '$status $body_bytes_sent "$http_referer" '
                     # '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log  /var/log/nginx/access.log  main;
        access_log  /dev/stdout;
        client_max_body_size 110m;
        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        #include /etc/nginx/conf.d/*.conf;

        server {
        listen       0.0.0.0:80;
        server_name  fs-dev.np-0000177.npause1.bakerhughes.com;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        #include /etc/nginx/default.d/*.conf;

        location /sdsts {
          rewrite /sdsts/(.*)$ /$1 break;
          proxy_pass http://svc-sdsts:80;
         }

        location /alrt {
         rewrite /alrt/(.*)$ /$1 break;
         proxy_pass http://svc-alerts-service:80;
        }
 
        location /alert2 {
         rewrite /alert2/(.*)$ /$1 break;
         proxy_pass http://svc-alert-service-2-0:80;
        }
        
        location /alert2-mgmt {
         rewrite /alert2-mgmt/(.*)$ /$1 break;
         proxy_pass http://svc-alert-service-2-0:3000;
        }
        
        location /casealert2 {
         rewrite /casealert2/(.*)$ /$1 break;
         proxy_pass http://svc-case-alert-2-0:80;
        }
        
        location /advisory {
         rewrite /advisorysvc/(.*)$ /$1 break;
         proxy_pass http://svc-advisories-service:80;
        }

        location /notes {
          rewrite /notes/(.*)$ /$1 break;
          proxy_pass http://svc-notes-service:80;
        }

        location /blobstore {
          rewrite /blobstore/(.*)$ /$1 break;
          #proxy_redirect off;
        proxy_pass http://svc-blob-store:80;
        }
        
        location /bh-auth {
          rewrite /bh-auth/(.*)$ /$1 break;
          proxy_pass http://svc-bhsecurityservice:80;
        }

        location /asset2 {
         rewrite /asset2/(.*)$ /$1 break;
         proxy_pass http://svc-asset-fs-service-2-0:80;
        }

        location /ast {
         rewrite /ast/(.*)$ /$1 break;
         proxy_pass http://svc-asset-service:80;
        }
        
        location /tenant-demo {
         rewrite /tenant-demo/(.*)$ /$1 break;
         proxy_pass http://svc-tenant-config-demo:80;
        }
        
        location /notification {
         rewrite /notification/(.*)$ /$1 break;
         proxy_pass http://svc-notification:80;
        }

        location /security-adapter {
         rewrite /security-adapter/(.*)$ /$1 break;
         proxy_pass http://svc-security-adapter:80;
        }

        location /zenko {
         rewrite /zenko/(.*)$ /$1 break;
         proxy_pass http://zenko-svc:8000;
        }
        
        location /zenko/live {
         rewrite /zenko/(.*)$ /$1 break;
         proxy_pass http://zenko-svc:8002;
        }
        
        location /zenko/ready {
         rewrite /zenko/(.*)$ /$1 break;
         proxy_pass http://zenko-svc:8002;
        }
        
        location /object-storage {
         rewrite /object-storage/(.*)$ /$1 break;
         proxy_pass http://svc-objectstorage-service:80;
        }
        
        location /tenantmgmt {
         rewrite /tenantmgmt/(.*)$ /$1 break;
         proxy_pass http://bh-tenant-mgmt-service:80;
        }
        
         location /auditingestion {
         rewrite /auditingestion/(.*)$ /$1 break;
         proxy_pass http://svc-auditingestion;
        }
        
        location /argocd {
          proxy_redirect off;
          proxy_pass http://argocd-server.argocd;
          proxy_http_version 1.1; # this is essential for chunked responses to work
          proxy_buffering    off;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Scheme $scheme;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   Host $http_host;
        }
        
        #location /test {
         #           default_type text/plain;
         #           return 200 'Welcome to test page for FS QA';
         #       }


    
        }
        }
