apiVersion: v1
kind: Service
metadata:
  name: svc-advisories-service
  labels:
    app: advisories-service
spec:
  type: NodePort
  ports:
  - name: advisories-app
    port: 80
    nodePort: 30200
    targetPort: 8000
  - name: postgres-db
    port: 5432
    targetPort: 5432
  selector:
    app: dep-advisories-service
