apiVersion: v1
kind: Service
metadata:
  name: svc-appshellusermngt
  labels:
    app: appshellusermngt
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30604
      targetPort: 8086
      protocol: TCP
      name: svc-appshellusermngt
  selector:
    app: dep-appshell-usermngt
