apiVersion: v1
kind: Service
metadata:
  name: svc-fastlci-svc
  labels:
    app: svc-fastlci-svc
spec:
  type: NodePort
  ports:
  - name: fastlci-svc
    port: 80
    nodePort: 32284
    targetPort: 7000
  - name: fastlci-svc-db
    port: 5432
    targetPort: 5432
  selector:
    app: dep-fastlci-svc
