apiVersion: v1
kind: Service
metadata:
  name: svc-notes-service
  labels:
    app: notes-service
spec:
  type: NodePort
  ports:
  - name: notes-app
    port: 80
    nodePort: 30216
    targetPort: 3000
  - name: postgres-db
    port: 5432
    targetPort: 5432
  selector:
    app: dep-notes-service
