apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts2-configmap
data: 
  initial-types.json: |
      [
        {
            "tenant" : "SPARQ-DEV",
            "initialdata" : [
              {
                "id": "DAPRTest22123Type98",
                "name": "DAPRTest22123Type98",
                "version": "1.0",
                "fields": [
                  {
                    "name": "inteventid",
                    "datatype": "bigint",
                    "default": "123456789"
                  },
                  {
                    "name": "enteredtime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "exittime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "columnthree",
                    "datatype": "text"
                  },
                  {
                    "name": "columnfour",
                    "datatype": "integer",
                    "default": "2344"
                  },
                  {
                    "name": "nodeid",
                    "datatype": "json"
                  },
                  {
                    "name": "roundid",
                    "datatype": "jsonb"
                  }
                ],
                "identity": "columnthree",
                "groupingkey": "columnthree",
                "partitionkey": "enteredtime",
                "partitionduration": "Y"
              },
              {
                "id": "DAPRTest22123Type120",
                "name": "DAPRTest22123Type120",
                "version": "1.0",
                "fields": [
                  {
                    "name": "inteventid",
                    "datatype": "bigint",
                    "default": "123456789"
                  },
                  {
                    "name": "enteredtime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "exittime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "columnthree",
                    "datatype": "text"
                  },
                  {
                    "name": "columnfour",
                    "datatype": "integer",
                    "default": "2344"
                  },
                  {
                    "name": "nodeid",
                    "datatype": "json"
                  },
                  {
                    "name": "roundid",
                    "datatype": "jsonb"
                  }
                ],
                "identity": "columnthree",
                "groupingkey": "columnthree",
                "partitionkey": "enteredtime",
                "partitionduration": "Y"
              }
            ]
            },
            {
            "tenant" : "0b241a24-22ea-4c0f-ab8b-2972c3d5b5cc",
            "initialdata" : [
              {
                "id": "DAPRTest22123Type130",
                "name": "DAPRTest22123Type130",
                "version": "1.0",
                "fields": [
                  {
                    "name": "inteventid",
                    "datatype": "bigint",
                    "default": "123456789"
                  },
                  {
                    "name": "enteredtime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "exittime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "columnthree",
                    "datatype": "text"
                  },
                  {
                    "name": "columnfour",
                    "datatype": "integer",
                    "default": "2344"
                  },
                  {
                    "name": "nodeid",
                    "datatype": "json"
                  },
                  {
                    "name": "roundid",
                    "datatype": "jsonb"
                  }
                ],
                "identity": "columnthree",
                "groupingkey": "columnthree",
                "partitionkey": "enteredtime",
                "partitionduration": "Y"
              },
              {
                "id": "DAPRTest22123Type149",
                "name": "DAPRTest22123Type149",
                "version": "1.0",
                "fields": [
                  {
                    "name": "inteventid",
                    "datatype": "bigint",
                    "default": "123456789"
                  },
                  {
                    "name": "enteredtime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "exittime",
                    "datatype": "timestamp"
                  },
                  {
                    "name": "columnthree",
                    "datatype": "text"
                  },
                  {
                    "name": "columnfour",
                    "datatype": "integer",
                    "default": "2344"
                  },
                  {
                    "name": "nodeid",
                    "datatype": "json"
                  },
                  {
                    "name": "roundid",
                    "datatype": "jsonb"
                  }
                ],
                "identity": "columnthree",
                "groupingkey": "columnthree",
                "partitionkey": "enteredtime",
                "partitionduration": "Y"
              }
            ]
            }
        ] 
  rbac.conf: |
   [
    {
        "path": "/v2/register",
        "methods": [
            {
                "method": "POST",
                "scopes": [
                    ":register-tenant"
                ]
            }
        ]
    },
    {
        "path": "/v2/alerts",
        "methods": [
            {
                "method": "POST",
                "scopes": ":create-alert"
            },
            {
                "method": "PATCH",
                "scopes": ":update-alert"
            }
        ]
    },
    {
        "path": "/v2/alerts/search",
        "methods": [
            {
                "method": "POST",
                "scopes": [
                    ":search-alert"
                ]
            }
        ]
    },
    {
        "path": "/v2/alerts/search/count",
        "methods": [
            {
                "method": "POST",
                "scopes": [
                    ":search-alert"
                ]
            }
        ]
    },
    {
        "path": "/v2/alerts/search-count",
        "methods": [
            {
                "method": "POST",
                "scopes": [
                    ":search-alert"
                ]
            }
        ]
    },
    {
        "path": "/v2/alerts/search/top-alert-within-subgroups",
        "methods": [
            {
                "method": "POST",
                "scopes": [
                    ":search-alert"
                ]
            }
        ]
    },
    {
        "path": "/v2/types",
        "methods": [
            {
                "method": "GET",
                "scopes": [
                    ":read-type"
                ]
            },
            {
                "method": "POST",
                "scopes": [
                    ":create-type"
                ]
            }         
        ]
    },
    {
        "path": "/v2/types/:typeId/fields",
        "methods": [
            {
                "method": "PATCH",
                "scopes": [
                    ":update-type"
                ]
            }
        ]
    }    
   ]
