apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-configmap-default
data:
  default.conf: |
    {
      "properties": {
        "DB_HOST": "fsdpgd05.c6ooanpu2tgf.us-east-1.rds.amazonaws.com",
        "DB_PORT": "5432",
        "DB_NAME": "postgres",
        "BROKER_CONNECTION_STRING" : "amqps://fsalert:AQBHk0iKSf28mGP6@b-f15207c5-bb94-4a13-8f93-216ff44cdb5b.mq.us-east-1.amazonaws.com:5671",
        "PG_TLS" : "true",
        "MQ_ENDPOINT" : "Alert_Topic",
        "ENABLE_NOTIFICATION": "true",
        "MAX_PAGE_SIZE": "3000",
        "ROUTING_KEYS": "tenant,source,groupId,operation,typeId",
        "SUB_GROUP_LIMITS": "3000,10000,50000,200000"
      },
      "secrets":{   
        "DB_USERNAME": "/app/tenant-info/DB_USERNAME",       
        "DB_PASSWORD": "/app/tenant-info/DB_PASSWORD",
        "BROKER_PASSWORD": "/app/tenant-info/BROKER_PASSWORD"
      }        
    }
