apiVersion: v1
kind: Service
metadata:
  name: svc-alert-service-2-0
  labels:
    app: alert-service-2-0
spec:
  type: NodePort
  ports:
  - name: alert-2-0-app
    port: 80
    nodePort: 30202
    targetPort: 8000
  - name: alert-app-2
    port: 3000
    nodePort: 30203
    targetPort: 3000
  - name: postgres-db
    port: 5432
    targetPort: 5432
  selector:
    app: dep-alert-service-2-0
