apiVersion: v1
kind: PersistentVolume
metadata:
  name: objectstorage-service-pv
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/efs-mount-point/fs-dev/objectstorage-pv
