apiVersion: v1
kind: Service
metadata:
  name: svc-app-shell
  labels:
    app: app-shell
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30309
      targetPort: 8000
      protocol: TCP
      name: svc-app-shell
    - port: 9000
      nodePort: 30603
      targetPort: 9000
      protocol: TCP
      name: ws-app-shell
  selector:
    app: dep-app-shell
