apiVersion: v1
kind: Service
metadata:
  name: svc-blob-store
  labels:
    app: blob-store
spec:
  type: NodePort
  ports:
    - name: blob-store-app
      port: 80
      nodePort: 30214
      targetPort: 8040
    - name: postgres-db
      port: 5432
      targetPort: 5432
  selector:
    app: dep-blob-store
